# Builds and runs unit tests for the examples
name: Test Examples

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.x

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Restore Bonsai.ML Dependencies
        run: dotnet restore src/Bonsai.ML.sln
  
      - name: Build Bonsai.ML
        run: dotnet build src/Bonsai.ML.sln

      - name: Restore Test Examples Dependencies
        run: dotnet restore docs/examples/test/Bonsai.ML.Examples.sln --configfile docs/examples/test/Bonsai.ML.Examples.Tests/NuGet.config

      - name: Run Tests
        run: dotnet test docs/examples/test/Bonsai.ML.Examples.sln
